package com.zpz.went.common.model;

import com.zpz.went.common.model.base.BaseBookDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookDetail extends BaseBookDetail<BookDetail> {

}
