package com.zpz.went.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBorrow<M extends BaseBorrow<M>> extends Model<M> implements IBean {

    public java.lang.Integer getBookId() {
        return getInt("book_id");
    }

    public M setBookId(java.lang.Integer bookId) {
        set("book_id", bookId);
        return (M) this;
    }

    public java.lang.Integer getUserId() {
        return getInt("user_id");
    }

    public M setUserId(java.lang.Integer userId) {
        set("user_id", userId);
        return (M) this;
    }

    public java.lang.Integer getBorrowNumb() {
        return getInt("borrowNumb");
    }

    public M setBorrowNumb(java.lang.Integer borrowNumb) {
        set("borrowNumb", borrowNumb);
        return (M) this;
    }

}
