package com.zpz.went.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.Integer getNumb() {
		return getInt("numb");
	}

	public M setNumb(java.lang.Integer numb) {
		set("numb", numb);
		return (M)this;
	}

}
