package com.zpz.went.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return getInt("id");
    }

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

    public java.lang.String getUsername() {
        return getStr("username");
    }

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

    public java.lang.String getPassword() {
        return getStr("password");
    }

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

}
